FROM registry.redhat.io/rhel9/python-39:latest

LABEL name="odh-notebook-rocm-python-3.9" \
      summary="ROCm Python 3.9 base image for ODH notebooks" \
      description="ROCm Python 3.9 builder image based on RHEL Stream 9 for ODH notebooks" \
      io.k8s.display-name="ROCm Python 3.9 base image for ODH notebooks" \
      io.k8s.description="ROCm Python 3.9 builder image based on Rhel9 for ODH notebooks" \
      authoritative-source-url="https://github.com/red-hat-data-services/notebooks" \
      io.openshift.build.commit.ref="main" \
      io.openshift.build.source-location="https://github.com/red-hat-data-services/notebooks/tree/main/amd/rhel9-python-3.9"

WORKDIR /opt/app-root/bin

ARG ROCM_VERSION=6.1
ARG AMDGPU_VERSION=6.1

# Install micropipenv to deploy packages from Pipfile.lock
RUN pip install --no-cache-dir -U "micropipenv[toml]"
COPY Pipfile.lock ./
RUN echo "Installing softwares and packages" && micropipenv install && rm -f ./Pipfile.lock

USER 0

# Install required packages 
RUN yum -y install git java-1.8.0-openjdk && \
    yum clean all && rm -rf /var/cache/yum

# Install ROCm AMD from:
# https://github.com/ROCm/ROCm-docker/blob/master/dev/Dockerfile-RHEL-7-complete
# Enable epel-release repositories
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    yum -y install bc bridge-utils glibc.i686 \
    numactl-libs libssh libunwind-devel \
    libunwind pciutils pciutils-libs \
    re2c doxygen elfutils-libelf-devel \
    expect numactl-devel pciutils-devel \
    qemu-kvm subversion dkms dpkg \
    dpkg-dev dpkg-perl fakeroot mesa-libGL && \
    yum clean all && rm -rf /var/cache/yum


# Install rocm and amdgpu binaries 
RUN yum install -y amdgpu-dkms rocm && \
    yum clean all && rm -rf /var/cache/yum

# Restore notebook user workspace
USER 1001

# Install the oc client
RUN curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz \
        -o /tmp/openshift-client-linux.tar.gz && \
    tar -xzvf /tmp/openshift-client-linux.tar.gz oc && \
    rm -f /tmp/openshift-client-linux.tar.gz

# Fix permissions to support pip in Openshift environments
RUN chmod -R g+w /opt/app-root/lib/python3.9/site-packages && \
    fix-permissions /opt/app-root -P

WORKDIR /opt/app-root/src
